spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql:///sql_executed?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    select-update:
      jdbc-url: jdbc:mysql:///select_update?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    delete-insert:
      jdbc-url: jdbc:mysql:///delete_insert?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver



